/** supabase/migrations/002_receipt_drafts.sql içeriği: uygulamadaki kurulum ekranından kopyalanır. */
export const DRAFTS_SETUP_SQL = "create table if not exists public.receipt_drafts (\n  id             uuid primary key default gen_random_uuid(),\n  user_id        uuid not null default auth.uid() references auth.users (id) on delete cascade,\n  created_at     timestamptz not null default now(),\n  image_path     text not null,\n  status         text not null default 'pending'\n                 check (status in ('pending', 'scheduled', 'processing', 'ready', 'failed')),\n  scheduled_for  timestamptz,\n  result         jsonb,\n  error          text\n);\n\ncreate index if not exists receipt_drafts_user_created_idx on public.receipt_drafts (user_id, created_at);\n\nalter table public.receipt_drafts enable row level security;\n\ndrop policy if exists \"drafts_select_own\" on public.receipt_drafts;\ncreate policy \"drafts_select_own\" on public.receipt_drafts\n  for select to authenticated using ((select auth.uid()) = user_id);\n\ndrop policy if exists \"drafts_insert_own\" on public.receipt_drafts;\ncreate policy \"drafts_insert_own\" on public.receipt_drafts\n  for insert to authenticated with check ((select auth.uid()) = user_id);\n\ndrop policy if exists \"drafts_update_own\" on public.receipt_drafts;\ncreate policy \"drafts_update_own\" on public.receipt_drafts\n  for update to authenticated\n  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);\n\ndrop policy if exists \"drafts_delete_own\" on public.receipt_drafts;\ncreate policy \"drafts_delete_own\" on public.receipt_drafts\n  for delete to authenticated using ((select auth.uid()) = user_id);\n\n-- Taslak görselleri AI'ın okuyabilmesi için daha yüksek çözünürlükte tutulur (kaydedilince silinir)\nupdate storage.buckets set file_size_limit = 1048576 where id = 'receipt-images';\n\n-- API'nin yeni tabloyu hemen tanıması için\nnotify pgrst, 'reload schema';\n";

/** supabase/migrations/004_giyim_category.sql içeriği (yorumlar hariç); 003 yapılmamış olsa da tek başına yeterli */
export const CATEGORIES_SETUP_SQL = "alter table public.receipts drop constraint if exists receipts_kategori_check;\nalter table public.receipts add constraint receipts_kategori_check check (kategori in (\n  'akaryakıt', 'restoran', 'market', 'teknoloji', 'ofis gideri',\n  'ulaşım', 'araç bakım', 'konaklama', 'iletişim', 'faturalar', 'kargo', 'giyim', 'diğer'\n));\n\n-- Uygulama kurulumun yapıldığını bu fonksiyondan anlar\ncreate or replace function public.receipt_schema_version() returns integer\n  language sql stable as $$ select 4 $$;\ngrant execute on function public.receipt_schema_version() to authenticated;\n\nnotify pgrst, 'reload schema';\n";

/** supabase/migrations/005_receipt_trash.sql içeriği (çöp kutusu; 004 kategorilerini de kapsar) */
export const TRASH_SETUP_SQL = "\ncreate table if not exists public.receipt_trash (\n  id          uuid primary key,\n  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,\n  deleted_at  timestamptz not null default now(),\n  receipt     jsonb not null\n);\n\ncreate index if not exists receipt_trash_user_deleted_idx on public.receipt_trash (user_id, deleted_at desc);\n\nalter table public.receipt_trash enable row level security;\n\ndrop policy if exists \"trash_select_own\" on public.receipt_trash;\ncreate policy \"trash_select_own\" on public.receipt_trash\n  for select to authenticated using ((select auth.uid()) = user_id);\n\ndrop policy if exists \"trash_insert_own\" on public.receipt_trash;\ncreate policy \"trash_insert_own\" on public.receipt_trash\n  for insert to authenticated with check ((select auth.uid()) = user_id);\n\ndrop policy if exists \"trash_delete_own\" on public.receipt_trash;\ncreate policy \"trash_delete_own\" on public.receipt_trash\n  for delete to authenticated using ((select auth.uid()) = user_id);\n\n-- 004: tüm kategoriler\nalter table public.receipts drop constraint if exists receipts_kategori_check;\nalter table public.receipts add constraint receipts_kategori_check check (kategori in (\n  'akaryakıt', 'restoran', 'market', 'teknoloji', 'ofis gideri',\n  'ulaşım', 'araç bakım', 'konaklama', 'iletişim', 'faturalar', 'kargo', 'giyim', 'diğer'\n));\n\n-- Uygulama kurulumun yapıldığını bu fonksiyondan anlar\ncreate or replace function public.receipt_schema_version() returns integer\n  language sql stable as $$ select 5 $$;\ngrant execute on function public.receipt_schema_version() to authenticated;\n\nnotify pgrst, 'reload schema';\n";

export const SUPABASE_SQL_EDITOR_URL = 'https://supabase.com/dashboard/project/fzhagwcysltvpcgdfrnl/sql/new';
